package com.entities;
// Generated Aug 18, 2023, 2:33:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
//@Entity
//@Table(name = "demo")
public class Demo implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String fullName;
	private String email;
	private boolean status;
	private Date dob;
//	@Temporal(TemporalType.DATE)
//	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Demo() {
	}

	public Demo(String username, String password, String fullName, String email, boolean status) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.email = email;
		this.status = status;
	}

	
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//
//	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	@Column(name = "username", nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

//	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

//	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

//	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

//	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}


}
